-- Disable RLS for testing
ALTER TABLE files DISABLE ROW LEVEL SECURITY;
ALTER TABLE folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE file_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE folder_permissions DISABLE ROW LEVEL SECURITY;